# Generated by Django 5.2.3 on 2025-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('movie_title', models.CharField(max_length=255)),
                ('seat', models.CharField(max_length=10)),
                ('show_time', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
