# Generated by Django 5.2.3 on 2025-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_moviebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='moviebooking',
            name='row_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moviebooking',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='moviebooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='moviebooking',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moviebooking',
            name='movie_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moviebooking',
            name='seat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moviebooking',
            name='show_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
