# Generated by Django 5.2.3 on 2025-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_moviebooking_amount_moviebooking_row_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
