# Generated by Django 5.2.3 on 2025-06-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dicegamescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicegamescore',
            old_name='played_at',
            new_name='date_played',
        ),
        migrations.RenameField(
            model_name='dicegamescore',
            old_name='player1_name',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='dicegamescore',
            old_name='player2_name',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='dicegamescore',
            old_name='player1_score',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='dicegamescore',
            old_name='player2_score',
            new_name='score2',
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wins', models.IntegerField(default=0)),
                ('spin_unlocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
