# Generated by Django 5.2.3 on 2025-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_played_at_dicegamescore_date_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=20)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
