# Generated by Django 5.2.3 on 2025-06-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount'),
        ),
    ]
