# Generated by Django 5.2.4 on 2025-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
                ('usercontact', models.IntegerField(unique=True)),
                ('userpass', models.CharField(max_length=50)),
            ],
        ),
    ]
