# Generated by Django 5.2.4 on 2025-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appedumaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
