# Generated by Django 5.2.4 on 2025-07-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appedumaster', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appedumaster.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appedumaster.lmsuser')),
            ],
        ),
    ]
