# Generated by Django 5.2.4 on 2025-07-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appedumaster', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
